[package]
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
description = "Simple cw4 implementation of group membership controlled by admin "
documentation = "https://docs.cosmwasm.com"
edition = "2018"
homepage = "https://cosmwasm.com"
license = "Apache-2.0"
name = "cw4-group"
repository = "https://github.com/CosmWasm/cw-plus"
version = "0.15.1"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "artifacts/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema = {version = "1.1.0"}
cosmwasm-std = {version = "1.1.0"}
cw-controllers = {version = "0.15.1"}
cw-storage-plus = "0.15.1"
cw-utils = {version = "0.15.1"}
cw2 = {version = "0.15.1"}
cw4 = {version = "0.15.1"}
schemars = "0.8.1"
serde = {version = "1.0.103", default-features = false, features = ["derive"]}
thiserror = {version = "1.0.23"}
